#!/bin/bash
# afl-update - Update to the latest version of afl

if (( $# != 0 ))
then
    echo "Usage: ${0##*/}"
    exit
fi

echo -n "Current version: "
current="$(afl-fuzz | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g ; q" | sed -e 's/^afl-fuzz \([^ ]\+\) .*$/\1/')"
echo "$current"

echo -n "Latest version: "
latest="$(wget -q -O - 'http://lcamtuf.coredump.cx/afl/ChangeLog.txt' | sed -ne '/^Version [^:]\+:$/ { s/^Version \([^:]\+\):$/\1/p ; q }')"
echo "$latest"
echo

[[ "$current" == "$latest" ]] && { echo "Already up-to-date!" ; exit ; }

read -r -p "Upgrade? [y/N] " ans
if [[ "${ans,,}" =~ ^y(es)?$ ]]
then
    echo
    wget -O "afl-${latest}.tar.gz" "http://lcamtuf.coredump.cx/afl/releases/afl-${latest}.tgz"
    tar xzvf "afl-${latest}.tar.gz"
    cd "afl-${latest}"
    make
    make install PREFIX="${PREFIX:-$HOME/.local}"
    make clean
    cd ..
    rm -rf "afl-${current}"
    rm -f "afl-${current}.tar.gz"

    echo
    new="$(afl-fuzz | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g ; q" | sed -e 's/^afl-fuzz \([^ ]\+\) .*$/\1/')"
    [[ "$new" == "$latest" ]] && echo "afl successfully updated to version $latest!" || echo "Upgrade failed!"
fi

