#!/bin/bash
# afl-update - Update to the latest version of afl

if (( $# != 0 ))
then
    echo "Usage: ${0##*/}"
    exit
fi

function aflversion() {
    afl-fuzz | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g ; q" | sed -e 's/^afl-fuzz \([^ ]\+\) .*$/\1/'
}

echo -n "Current version: "
current="$(aflversion)"
echo "$current"

function cleanup () {
    rm -f "$changelog"
}
trap cleanup EXIT

echo -n "Latest version: "
changelog="$(mktemp --tmpdir afl-changelog-XXXXXX)"
wget -q -O "$changelog" 'http://lcamtuf.coredump.cx/afl/ChangeLog.txt'
latest="$(sed -ne '/^Version [^:]\+:$/ { s/^Version \([^:]\+\):$/\1/p ; q }' "$changelog")"
echo "$latest"
echo

[[ "$current" == "$latest" ]] && { echo "Already up-to-date!" ; exit ; }

read -r -p "Upgrade? [y/N] " ans
if [[ "${ans,,}" =~ ^y(es)?$ ]]
then
    echo
    wget -O "afl-${latest}.tar.gz" "http://lcamtuf.coredump.cx/afl/releases/afl-${latest}.tgz"
    tar xzf "afl-${latest}.tar.gz"
    cd "afl-${latest}"
    make
    make install PREFIX="${PREFIX:-$HOME/.local}"
    make clean
    cd ..

    echo
    if [[ "$(aflversion)" == "$latest" ]]
    then
        rm -rf "afl-${current}"
        rm -f "afl-${current}.tar.gz"

        echo "Changelog:"
        echo
        awk -v FROM="$current" -f - -- "$changelog" <<- "_EOF_"
			BEGIN {
			    do_print = 0
			}
			/^Version .*/ {
			    if (do_print) {
			        match($0, "^Version ([^:]+):", a)
			        if (a[1] == FROM) {
			            exit
			        }
			    }
			    do_print = 1
			    print "    --------------"
			    print "    " $0
			    print "    --------------"
			    next
			}
			/^-+$/ {
			    next
			}
			{
			    if (do_print) {
			        print "    " $0
			    }
			}
			_EOF_

        echo "afl successfully updated to version $latest!"
        echo
    else
        echo "Upgrade failed!"
    fi
fi

# vim: ts=4
