#!/bin/bash
# build ctags and cscope tags in the current directory

exts=(c h x s S l y C H cc cpp hh hpp "$@")
if [[ -f .ignore ]]; then
    # honor .ignore
    ctags -R --extras=fq --fields=afikKlmnsSzt --exclude=@.ignore
    # disable pathname expansion since it occurs *after* command substitution and wrecks the arguments generated with $(printf -- " -name *.%s -o ") (and I can't seem to escape the *)
    set -f
    find . $(printf -- '-path ./%s -prune -o ' $(<.ignore)) -type f \( $(printf -- "-name *.%s -o " "${exts[@]}") -false \) -print | cscope -b -i-
else
    # no .ignore
    ctags -R --extras=fq --fields=afikKlmnsSzt .
    # disable pathname expansion since it occurs *after* command substitution and wrecks the arguments generated with $(printf -- " -name *.%s -o ") (and I can't seem to escape the *)
    set -f
    find . -type f \( $(printf -- '-name *.%s -o ' "${exts[@]}") -false \) -print | cscope -b -i-
fi
