#!/bin/bash
# build ctags and cscope tags in the current directory

exts=(c h x s S l y C H cc cpp hh hpp "$@")
find_exts=()
for e in "${exts[@]}"; do find_exts+=(-name "*.$e" -o); done
[[ -v VERBOSE ]] && echo 'exts=(' "${exts[@]}" ')'

ctags_ignore=()
find_ignore=()

ignore() {
    local pattern
    while read -r pattern; do
        # remove trailing / since it doesn't play well with `ctags --exclude` or `find -path`
        pattern="${pattern%/}"
        ctags_ignore+=(--exclude="$pattern")
        find_ignore+=(-path ./"$pattern" -prune -o)
    done
}

[[ -f .ignore ]] && ignore <.ignore
[[ -f .gitignore ]] && ignore <.gitignore

[[ -v VERBOSE ]] && echo find . "${find_ignore[@]}" -type f \( "${find_exts[@]}" -false \) -print \>cscope.files
find . "${find_ignore[@]}" -type f \( "${find_exts[@]}" -false \) -print >cscope.files
[[ -v VERBOSE ]] && echo ctags -R --extras=fq --fields=afikKlmnsSzt "${ctags_ignore[@]}" -L cscope.files
ctags -R --extras=fq --fields=afikKlmnsSzt "${ctags_ignore[@]}" -L cscope.files
[[ -v VERBOSE ]] && echo cscope -b
cscope -b
