#!/bin/bash
# build ctags and cscope tags in the current directory

exts=(c h x s S l y C H cc cpp hh hpp "$@")
cscope_exts=($(printf -- "-name *.%s -o " "${exts[@]}"))

ctags_ignore=()
cscope_ignore=()

#disable pathname expansion since it occurs *after* command substitution and wrecks the arguments generated with $(printf ...)
set -f

ignore() { # 1:filename
    # FIXME: this doesn't do well with spaces...
    # use sed to remove trailing /s since they don't play well with ctags or find's -path
    ctags_ignore+=($(printf -- '--exclude=%s ' $(sed -e 's|/$||' "$1")))
    cscope_ignore+=($(printf -- '-path ./%s -prune -o ' $(sed -e 's|/$||' "$1")))
}

[[ -f .ignore ]] && ignore .ignore
[[ -f .gitignore ]] && ignore .gitignore

ctags -R --extras=fq --fields=afikKlmnsSzt "${ctags_ignore[@]}"
find . "${cscope_ignore[@]}" -type f \( "${cscope_exts[@]}" -false \) -print | cscope -b -i-
