#!/bin/bash

# Not the required number of arguments: display the help
if [[ $# != 3 ]]
then
    echo "  Usage: ${0##*/} <amount> <from> <to>"
    echo "Unit/currency converter using Google's calculator."
    exit
fi

# Source some useful functions
source ${0%/*}/../bash/modules/url

# Switch to C locale (Google returns some weird characters which we'd have to convert from ISO8859-1 to UTF-8 otherwise)
export LANG=C

# Query
RESULT="`curl -s "http://www.google.com/ig/calculator?hl=en&q=$(urlencode $1)$(urlencode $2)=?$(urlencode $3)&#8221"`"

# Check for error
ERROR="`echo "$RESULT" | sed -e 's/^{lhs: "[^"]*",rhs: "[^"]*",error: "\([^"]*\)".*$/\1/'`"
if [[ -n "$ERROR" ]]
then
    echo "Error: $ERROR" >&2
    exit 1
fi

# Print response (filter out garbage characters)
echo "$RESULT" | sed -e 's/^{lhs: "[^"]*",rhs: "\([^ ]*\)[^"]*".*$/\1/' | tr -cd '0-9.\n'

