#!/bin/bash

if [[ $# -ne 1 || "$1" == "-h" || "$1" == "--help" ]]
then
    echo "Usage: ${0##*/} <directory>"
    exit
fi

find "$1" -type d -printf '%P\0' | xargs -0 -I{} bash -c 'echo $((`echo "$1" | grep -o / | wc -l`+1)) "$1"' -- {} | sort -rug -k1 --parallel=8 | head -n 1

