#!/bin/bash

[[ -S "$SSH_AUTH_SOCK" ]] || { echo "error: bad agent socket: $SSH_AUTH_SOCK"; exit 1; }

args=()
[[ -n "$SSH_SESSION_KEY_LIFETIME" ]] && args+=(-t "$SSH_SESSION_KEY_LIFETIME")

# Don't attempt to add a literal ~/.ssh/session-keys.d/* file to the agent if the directory is empty
shopt -s nullglob

keys=(~/.ssh/session-keys.d/*)

# ssh-add exits with a non-0 exit code when there are no keys provided on the command line
# Bail successfully if that would be the case
(( ${#keys[@]} == 0 )) && exit 0

# Add all keys in ~/.ssh/session-keys.d
ssh-add "${args[@]}" ~/.ssh/session-keys.d/*
