#!/bin/bash
# die - print a message and exit on error, preserving original error code

function die() {
    # Get return code
    local RC=$?
    local PREFIX="Error: "
    # Parse arguments (don't die on unknown arg, we're already dying)
    while [[ $# -gt 1 ]]
    do
        case "$1" in
            -i|--inline)
                PREFIX=""
                ;;

            -p*|--prefix)
                PREFIX=""
                [[ "${1:0:2}" == "-p" ]] && PREFIX=${1#-p}
                [[ -z "$PREFIX" ]] && { PREFIX="$2" ; shift ; }
                ;;

            -r*|--return)
                RC=""
                [[ "${1:0:2}" == "-r" ]] && RC=${1#-r}
                [[ -z "$RC" ]] && { RC="$2" ; shift ; }
                ;;
        esac
        shift
    done
    # Print message
    echo -e "$PREFIX$1" 1>&2
    # Exit with return code (return if interactive)
    [[ $- == *i* ]] && return $RC || exit $RC
}

