#!/bin/bash
# gpg-agent-test - test for a running GPG agent

function gpg-agent-test() {
    [[ $# -ne 1 ]] && { echo "Usage: $FUNCNAME <env-file>" >&2 ; return 1 ; }

    local gpg_agent_binary=/usr/bin/gpg-agent
    local gpg_agent_envfile="$1"

    # Test for the env file
    [[ ! -f "$gpg_agent_envfile" ]] && return 1

    # Source env file
    . "$gpg_agent_envfile"
    # Test for the agent info
    [[ -z "$GPG_AGENT_INFO" ]] && return 1

    # Get the agent PID
    local gpg_agent_pid=$(echo $GPG_AGENT_INFO | cut -d: -f2)
    # Test for ownership and validity of the PID
    [[ -O "/proc/$gpg_agent_pid" && "$gpg_agent_binary" -ef "/proc/$gpg_agent_pid/exe" ]] || { unset GPG_AGENT_INFO ; return 1 ; }

    # All checks passed: valid agent
    return 0
}

