#!/bin/bash
# ssh-agent-test - test for a running SSH agent
# ssh-agent-respawn - restart the SSH agent


# SSH keys to load automatically on agent restart
declare -a export SSH_AGENT_AUTOKEYS
export SSH_AGENT_AUTOKEYS


function ssh-agent-test() {
    [[ $# -ne 1 ]] && { echo "Usage: $FUNCNAME <env-file>" >&2 ; return 1 ; }

    local ssh_agent_envfile="$1"

    # Test for the env file
    [[ ! -f "$ssh_agent_envfile" ]] && return 1

    # Source env file
    . "$ssh_agent_envfile" &> /dev/null
    # Test the agent
    ssh-add -l &> /dev/null
    [[ $? -eq 2 ]] && return 1

    # All checks passed: valid agent
    return 0
}


function ssh-agent-respawn() {
    [[ $# -ne 1 ]] && { echo "Usage: $FUNCNAME <env-file>" >&2 ; return 1 ; }

    local ssh_agent_envfile="$1"

    # Kill all existing agents for the current user
    # (SSH_AGENT_PID may not be set so we can't use `ssh-agent -k`)
    killall -r -u "$(id -un)" ssh-agent

    # Start the agent
    ssh-agent -s > "$ssh_agent_envfile"
    . "$ssh_agent_envfile"

    # Add auto keys
    ssh-add "${SSH_AGENT_AUTOKEYS[@]}"

    return 0
}

