#!/bin/bash

: "${CHROOT_BASE:=/mnt/gentoo}"

mountpoint -q "$CHROOT_BASE" || { echo "Error: $CHROOT_BASE not mounted" ; return ; }

mount -v -t proc none "$CHROOT_BASE/proc"
mount -v --rbind /sys "$CHROOT_BASE/sys"
mount -v --make-rslave "$CHROOT_BASE/sys"
mount -v --rbind /dev "$CHROOT_BASE/dev"
mount -v --make-rslave "$CHROOT_BASE/dev"

alias chroot-gentoo="chroot $CHROOT_BASE /bin/bash"
cat <<EOF

Live CD environment setup for chrooting into $CHROOT_BASE.
Enter the chroot with:                  chroot-gentoo
Once inside, setup the environment:     source chroot-env
EOF
