#!/bin/bash
# "Fix" the title tags of audio tracks by prepending them with the track #

if [[ $# -lt 1 || "$1" == "-h" || "$1" == "--help" ]]
then
    cat <<- _EOF_
	  Usage: ${0##*/} <directories>
	
	Prepend the track # to the title tag of audio tracks in a directory.
	For MP3, also convert the id3 tags to v2.4, stripping all other versions.
	
	Supported file formats:
	    mp3
	    ogg
	    flac
	
	Note:
	* The first space-delimited block of characters in the filename is assumed to
	  be the track # (this is highly tied to the organization of my library).
	* The main purpose of this tool is to work around a misfeature of my ISP's
	  shitty DLNA music player, which orders tracks alphabetically by title tag
	  -- not even by filename! *sigh*
	
	_EOF_
    exit
fi

function require() {    #1:tool [2:variable] [3+:paths]
    local tool="$1"
    local var="$2"
    [[ -z "$var" ]] && var="$tool"
    shift 2
    if command -v "$tool" &> /dev/null
    then
        eval $var="\$tool"
        return
    fi
    for p in "$@"
    do
        if command -v "$p/$tool" &> /dev/null
        then
            if [[ "${p:0:1}" == "/" ]]
            then
                eval $var="\$p/\$tool"
            else
                eval $var="\$PWD/\$p/\$tool"
            fi
            return
        fi
    done

    echo "Error: the \`$tool\` utility is required but not found in your PATH!" >&2
    exit 1
}

function trackno() {    #1:file
    printf "${1%% *}"
}

function tracktitle() { #1:file [2:escape]
    local title
    case "${1##*.}" in
        mp3)
            title="$($id3ted -l "$1" | sed -ne '/^TIT2:/ s/TIT2: //p')"
            ;;
        ogg)
            title="$($vorbiscomment -l "$1" | sed -ne '/^title=/ s/title=//p')"
            ;;
        flac)
            title="$($metaflac --list "$1" | sed -ne '/^ *comment\[[0-9]\+\]: TITLE=/ s/^.*=//p')"
            ;;
    esac
    if (( ${2:-0} ))
    then
        sed -e 's,/,\/,g' -e 's/&/\&/g' "$1" <<< "$title"
    else
        echo "$title"
    fi
}

# Check for required utilities
require id3ted
require vorbiscomment
require vorbised vorbised "${0%/*}"
require metaflac
require sedaflac sedaflac "${0%/*}"

# Don't use * literally when no files are matched
shopt -s nullglob
# Don't bother with the case of the file extension
shopt -s nocaseglob
shopt -s nocasematch

quiet=0

for d in "$@"
do
    cd "$d"
    d="${d%/}"
    proceed=1
    refresh=1
    empty=1
    if ! (( $quiet ))
    then
        while (( $refresh ))
        do
            refresh=0
            printf "Overview for '%s':" "$d"
            for f in *.mp3 *.ogg *.flac
            do
                empty=0
                printf "\n  %s - %s" "$(trackno "$f")" "$(tracktitle "$f")"
            done
            if (( $empty ))
            then
                printf "\E[2K\rSkipping '%s': no tracks\n" "$d"
                proceed=0
            else
                echo
                read -r -p "Proceed? [y/N/r] " proceed
                case "$proceed" in
                    y|Y) proceed=1 ;;
                    n|N) proceed=0 ;;
                    r|R) refresh=1 ;;
                esac
            fi
        done
    fi
    if (( $proceed ))
    then
        for f in *.mp3 *.ogg *.flac
        do
            empty=0
            printf "\E[2K\rProcessing '%s'... %s" "$d" "$f"
            case "${f##*.}" in
                mp3)
                    $id3ted -2 "$f"
                    $id3ted -t "$(trackno "$f") - $(tracktitle "$f")" "$f"
                    $id3ted -s "$f"
                    ;;
                ogg)
                    $vorbised 's/^title=\(.*\)/title='"$(trackno "$f" 1)"' - '"$(tracktitle "$f" 1)"'/' "$f"
                    ;;
                flac)
                    $sedaflac 's/^TITLE=\(.*\)/TITLE='"$(trackno "$f" 1)"' - '"$(tracktitle "$f" 1)"'/' "$f"
                    ;;
            esac
        done
        if (( $empty ))
        then
            printf "Skipping '%s': no tracks\n" "$d"
        else
            printf "\E[2K\rProcessing '%s'... done\n" "$d"
        fi
    fi
    (( $quiet )) || echo
    cd "$OLDPWD"
done

