#!/bin/bash

if [[ $# -lt 2 || "$1" == "-h" || "$1" == "--help" ]]
then
    echo "Usage: ${0##*/} <sed script> <file ...>"
    exit
fi

sedscript="$1"
shift

# Sed and apply the tags in two steps to avoid unsetting all tags in case of a sed script error
for f in "$@"
do
    tags="$(metaflac --export-tags-to=- "$f" | sed -e "$sedscript")" || continue
    metaflac --remove-all-tags --import-tags-from=- "$f" <<< "$tags"
done

