#!/bin/bash

if [[ $# -lt 2 || "$1" == "-h" || "$1" == "--help" ]]
then
    echo "Usage: ${0##*/} <sed script> <file ...>"
    exit
fi

sedscript="$1"
shift

# Sed and apply the comments in two steps to avoid unsetting all comments in case of a sed script error
for f in "$@"
do
    comments="$(vorbiscomment -le "$f" | sed -e "$sedscript")" || continue
    vorbiscomment -we "$f" <<< "$comments"
done

