#!/bin/bash

# Source some useful functions
source ${0%/*}/../../bash/functions/die

# Help message
if [[ "$1" == "-h" || "$1" == "--help" ]]
then
    echo "Usage: ${0##*/}

Remove all files (except hidden ones) in the directory specified by the DISTDIR
environment variable. If unset, it is sourced from Portage's make.conf. If
still unset, it defaults to /usr/portage/distfiles." >&2
    exit
fi

# DISTDIR unset: source Portage config or default to /usr/portage/distfiles
[[ -z "$DISTDIR" ]] && . /etc/portage/make.conf
[[ -z "$DISTDIR" ]] && DISTDIR=/usr/portage/distfiles

# Check that the directory exists
[[ ! -d "$DISTDIR" ]] && die "directory $DISTDIR does not exist"

# Get the size of the directory contents (except dotfiles)
SIZE=$(du -sch "$DISTDIR"/* 2> /dev/null)
STATUS=$?
SIZE=$(echo "$SIZE" | tail -n 1 | cut -f1)
if [[ $STATUS != 0 ]]
then
    [[ $SIZE == 0 ]] && die -i -r0 "Directory $DISTDIR is empty."
    die "failed to stat contents of $DISTDIR"
fi

# Confirm then delete everything (except dotfiles) in the distfiles directory
echo -n "Purge $DISTDIR? ($SIZE) [y/N] "
declare -u ANS
read ANS
[[ "$ANS" == "Y" ]] && rm -Rf "$DISTDIR"/*

