#!/bin/bash
# Simple screenshot script for Sway
# Heavily adapted from https://github.com/de-arl/slurpshot
# Dependencies: cut, grim, imv, jq, notify-send, slurp, wl-copy, wofi

# Choose directory to save screenshots and viewer
shotpath=$(xdg-user-dir PICTURES)
viewer=/usr/bin/imv
viewer_appid=imv

menu() {
    wofi --show=dmenu --gtk-dark --width=400 --height=260 --cache-file=/dev/null "$@"
}

readarray -t windows < <(swaymsg -t get_tree | jq --raw-output '.. | ((.nodes?, .floating_nodes?) // empty)[] | select(.visible and .pid) | "Window: \(.app_id) \(.rect.x),\(.rect.y) \(.rect.width)x\(.rect.height)"')

focused=$(swaymsg -t get_tree | jq --raw-output '.. | ((.nodes?, .floating_nodes?) // empty)[] | select(.focused and .pid) | .rect | "\(.x),\(.y) \(.width)x\(.height)"')
focus_opt=()
[[ -n "$focused" ]] && focus_opt+=(Focus)

if [[ -z "$1" ]]; then
    choice=$(printf '%s\n' Fullscreen Selection "${focus_opt[@]}" "${windows[@]}" Abort | menu --prompt="Screenshot area:")
    if (( $? == 1 )); then
        exit 0
    fi
else
    choice="$1"
    case "$choice" in
        Fullscreen|Selection|Focus)
            # Valid option, carry on
            ;;

        *)
            echo "Error: Invalid option: $choice" >&2
            exit 1
            ;;
    esac
fi

filename="${shotpath}/screenshot-$(date +%Y%m%dT%H%M%S).png"
grid=$(cut -d' ' -f 3,4 <<<"$choice")

# Name printed when viewing screenshot, adjust if you edit $filename
filename_short=${filename: -30}

case "$choice" in
    Fullscreen)
        grim "$filename"
        ;;

    Selection)
        grim -g "$(slurp)" "$filename"
        ;;

    Focus)
        grim -g "$focused" "$filename"
        ;;

    Abort)
        exit 0
        ;;

    *)
        grim -g "$grid" "$filename"
        ;;
esac

again=true
while $again; do
    again=false

    # Monitor sway events waiting for the viewer window to pop, and make it float
    (
        pid=$(swaymsg --monitor --type subscribe '["window"]' | jq --arg viewer_appid "$viewer_appid" 'select(.change == "new" and .container.app_id == $viewer_appid) | (.container.pid, halt)') && \
            swaymsg '[pid='"$pid"'] floating enable'
    ) &

    $viewer "$filename" &
    viewer_pid=$!

    ans=$(printf '%s\n' Save Copy Discard "Hide menu" | menu --location=bottom --prompt="Screenshot: $filename_short")

    if (( $? == 1 )); then 
        kill -TERM "$viewer_pid"
        rm "$filename"
        exit 0
    fi

    case "$ans" in
        Save)
            kill -TERM "$viewer_pid"
            notify-send --urgency=low "Screenshot saved" "$filename"
            ;;

        Copy)
            kill -TERM "$viewer_pid"
            wl-copy --type image/png <"$filename"
            rm "$filename"
            notify-send --urgency=low "Screenshot copied to clipboard"
            ;;

        Discard)
            kill -TERM "$viewer_pid"
            rm "$filename"
            ;;

        "Hide menu")
            wait -f "$viewer_pid"
            again=true
            ;;
    esac
done

exit 0

# vim: ts=4 sts=4 sw=4 et
